import type { Data } from "./types";
export function demoData(day: string): Data {
  const stamp = (h: number) =>
    new Date(`${day}T${String(h).padStart(2, "0")}:00:00`).toISOString();
  return {
    couple: {
      id: "demo",
      member_one: "azhar",
      member_two: "ilias",
      timezone: Intl.DateTimeFormat().resolvedOptions().timeZone,
      day_start: 480,
      day_end: 1320,
      minimum_window: 30,
      buffer: 0,
      default_penalty: 2500,
    },
    profiles: [
      { id: "azhar", name: "Azhar", nickname: "azhar" },
      { id: "ilias", name: "Ilias", nickname: "ilias" },
    ],
    events: [
      {
        id: "e1",
        couple_id: "demo",
        user_id: "azhar",
        day,
        title: "Design studio",
        start_min: 480,
        end_min: 630,
        shared: false,
      },
      {
        id: "e2",
        couple_id: "demo",
        user_id: "ilias",
        day,
        title: "Team meeting & focused work",
        start_min: 510,
        end_min: 690,
        shared: false,
      },
      {
        id: "e3",
        couple_id: "demo",
        user_id: "azhar",
        day,
        title: "Project review",
        start_min: 660,
        end_min: 810,
        shared: false,
      },
      {
        id: "e4",
        couple_id: "demo",
        user_id: "ilias",
        day,
        title: "A few things to finish",
        start_min: 720,
        end_min: 810,
        shared: false,
      },
      {
        id: "e5",
        couple_id: "demo",
        user_id: "azhar",
        day,
        title: "Back to the studio",
        start_min: 900,
        end_min: 1080,
        shared: false,
      },
      {
        id: "e6",
        couple_id: "demo",
        user_id: "ilias",
        day,
        title: "Afternoon shift",
        start_min: 930,
        end_min: 1200,
        shared: false,
      },
      {
        id: "e7",
        couple_id: "demo",
        user_id: "azhar",
        day,
        title: "Pilates & the way home",
        start_min: 1140,
        end_min: 1320,
        shared: false,
      },
    ],
    ready: ["azhar", "ilias"].map((user_id) => ({
      couple_id: "demo",
      user_id,
      day,
    })),
    tasks: [
      {
        id: "t1",
        couple_id: "demo",
        creator_id: "azhar",
        assignee_id: "azhar",
        title: "Pick up the parcel",
        description: "The collection code is in our notes.",
        due_at: stamp(19),
        penalty: 2500,
        accepted_at: stamp(8),
        completed_at: null,
        confirmed_at: null,
        paid_at: null,
        declined_at: null,
        cancelled_at: null,
        waived_at: null,
        created_at: stamp(8),
      },
      {
        id: "t2",
        couple_id: "demo",
        creator_id: "ilias",
        assignee_id: "ilias",
        title: "Book our Friday table",
        description: "Somewhere quiet, by the window.",
        due_at: stamp(21),
        penalty: 3000,
        accepted_at: stamp(8),
        completed_at: null,
        confirmed_at: null,
        paid_at: null,
        declined_at: null,
        cancelled_at: null,
        waived_at: null,
        created_at: stamp(8),
        extension_requested_at: null,
        extension_requested_by: null,
        requested_due_at: null,
        extension_note: "",
      },
    ],
    notes: [
      {
        id: "n1",
        couple_id: "demo",
        author_id: "azhar",
        title: "For Friday",
        body: "A quiet table by the window. No rush.",
        pinned: true,
        created_at: stamp(8),
      },
      {
        id: "n2",
        couple_id: "demo",
        author_id: "ilias",
        title: "Parcel collection",
        body: "Code 4821 · the collection point on Abay.",
        pinned: false,
        created_at: stamp(9),
      },
      {
        id: "n3",
        couple_id: "demo",
        author_id: "azhar",
        title: "A little weekend idea",
        body: "A walk by the lake. And coffee on the way.",
        pinned: false,
        created_at: stamp(10),
      },
    ],
    messages: [
      {
        id: "m1",
        couple_id: "demo",
        sender_id: "ilias",
        body: "Looks like we both have a little space at half past one.",
        created_at: stamp(11),
      },
      {
        id: "m2",
        couple_id: "demo",
        sender_id: "azhar",
        body: "Lunch in the little square?",
        created_at: stamp(11),
      },
      {
        id: "m3",
        couple_id: "demo",
        sender_id: "ilias",
        body: "Yes. I’ll bring us coffee ☕",
        created_at: stamp(12),
      },
    ],
    messageReads: [
      { couple_id: "demo", user_id: "azhar", last_read_at: stamp(12) },
      { couple_id: "demo", user_id: "ilias", last_read_at: stamp(12) },
    ],
    notifications: [],
  };
}
